#!/usr/bin/env bash
# Build a repository and install from it with a real apt.
#
#   ./script/round-trip.sh
#
# This is M1's acceptance test, and it is a script rather than a Go test so that
# it can be run by hand on any Debian or Ubuntu machine, and so that CI runs the
# same thing a maintainer would.
#
# Nothing here is mocked. The packages are built by dpkg-deb, the key is
# generated by gpg, the signature is checked by apt against that key, and the
# package is installed by dpkg. If this passes, the repository is real.
#
# It needs root, because installing a package does. Run it in a container.
set -euo pipefail

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
# apt drops privileges to the _apt user before fetching, even from file://, and
# mktemp -d creates a directory only root can enter. Without this the download
# fails with a permission error that looks nothing like a permission error.
chmod 755 "$WORK"

ARCHIVIST="${ARCHIVIST:-./bin/archivist}"
if ! [ -x "$ARCHIVIST" ]; then
  echo "no archivist binary at $ARCHIVIST; run 'make build' or set ARCHIVIST" >&2
  exit 1
fi
ARCHIVIST="$(cd "$(dirname "$ARCHIVIST")" && pwd)/$(basename "$ARCHIVIST")"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# --- Packages ---------------------------------------------------------------
# Built with dpkg-deb rather than by us, so that what apt reads was produced by
# Debian's own tool. A generator and a reader written together can be wrong
# together.
say "Building packages with dpkg-deb"
mkdir -p "$WORK/dist"
build_package() {
  local name="$1" version="$2" arch="$3"
  # Split from the line above deliberately: bash expands every word of a `local`
  # before assigning any of them, so $name would still be unset here.
  local root="$WORK/build/$name"
  mkdir -p "$root/DEBIAN" "$root/usr/share/archivist-test"
  cat > "$root/DEBIAN/control" <<EOF
Package: $name
Version: $version
Architecture: $arch
Maintainer: Archivist CI <ci@example.invalid>
Section: misc
Priority: optional
Description: Synthetic package for the archivist round trip
 Installed by CI to prove that a generated repository is a real one.
EOF
  echo "$name $version" > "$root/usr/share/archivist-test/$name"
  dpkg-deb --build --root-owner-group "$root" "$WORK/dist/${name}_${version}_${arch}.deb" >/dev/null
}

HOST_ARCH="$(dpkg --print-architecture)"
build_package archivist-round-trip 1.0.0 "$HOST_ARCH"
build_package archivist-round-trip-doc 1.0.0 all

# A release directory is not only packages, and archivist must ignore the rest
# by looking at content rather than at names.
echo "not a package" > "$WORK/dist/checksums.txt"
echo "not a package either" > "$WORK/dist/decoy.deb"

# --- Signing key ------------------------------------------------------------
# Generated here and thrown away with the container. No secret is involved, so
# this job runs on a fork's pull request like any other.
say "Generating a throwaway signing key"
export GNUPGHOME="$WORK/gnupg"
mkdir -p "$GNUPGHOME"
chmod 700 "$GNUPGHOME"
gpg_batch() { gpg --batch --pinentry-mode loopback --passphrase '' "$@"; }

gpg_batch --quick-generate-key "Archivist Round Trip <ci@example.invalid>" rsa2048 cert 1y
PRIMARY="$(gpg --batch --list-keys --with-colons | awk -F: '$1=="fpr"{print $10; exit}')"
gpg_batch --quick-add-key "$PRIMARY" rsa2048 sign 1y
SUBKEY="$(gpg --batch --list-keys --with-colons \
  | awk -F: '$1=="sub"{seen=1} $1=="fpr" && seen {print $10; exit}')"

# The trailing "!" restricts the export to this subkey. Without it the primary's
# private material goes too, and archivist refuses the key - which is the point.
ARCHIVIST_GPG_KEY="$(gpg_batch --armor --export-secret-subkeys "${SUBKEY}!")"
export ARCHIVIST_GPG_KEY

cat > "$WORK/archivist.yml" <<EOF
origin: Archivist Round Trip
label: Archivist round trip packages
description: Built by CI to prove the repository is real
suite: stable
codename: stable
components: [main]
architectures: [$HOST_ARCH]
signing:
  key_id: $SUBKEY
EOF

# --- Build ------------------------------------------------------------------
say "Building the repository"
"$ARCHIVIST" build "$WORK/dist" --config "$WORK/archivist.yml" --out "$WORK/repo"

say "Refusing a key that can certify"
# The rule in docs/Signing-Keys.md is enforced, not recommended. Assert it here
# too: a guard that is only unit-tested is a guard that can be wired up wrong.
if ARCHIVIST_GPG_KEY="$(gpg_batch --armor --export-secret-keys "$PRIMARY")" \
     "$ARCHIVIST" build "$WORK/dist" --config "$WORK/archivist.yml" --out "$WORK/rejected" 2>"$WORK/refusal"; then
  echo "FAIL: a full secret key was accepted" >&2
  exit 1
fi
grep -q "certify" "$WORK/refusal" || { echo "FAIL: refused for the wrong reason:"; cat "$WORK/refusal"; exit 1; }
sed 's/^/    /' "$WORK/refusal"

# --- Install ----------------------------------------------------------------
say "Installing from the repository with apt"
install -d /etc/apt/keyrings
cp "$WORK/repo/public.gpg" /etc/apt/keyrings/archivist-round-trip.gpg
echo "deb [signed-by=/etc/apt/keyrings/archivist-round-trip.gpg] file://$WORK/repo stable main" \
  > /etc/apt/sources.list.d/archivist-round-trip.list

# apt warns rather than fails on a repository it cannot verify, so the output is
# inspected as well as the exit status.
apt-get update -o Acquire::Retries=0 2>&1 | tee "$WORK/update.log"
if grep -Eq "NO_PUBKEY|BADSIG|is not signed|EXPKEYSIG" "$WORK/update.log"; then
  echo "FAIL: apt could not verify the repository" >&2
  exit 1
fi

apt-get install -y --no-install-recommends archivist-round-trip archivist-round-trip-doc

for f in /usr/share/archivist-test/archivist-round-trip /usr/share/archivist-test/archivist-round-trip-doc; do
  [ -f "$f" ] || { echo "FAIL: $f was not installed" >&2; exit 1; }
done

say "Detecting a tampered index"
# A signature is worth nothing unless breaking the chain breaks the update.
# Two links get tested, because they fail in different places.

# Link one: Release lists a checksum for every index. Drop the compressed
# variant so apt must read the plain one, then change it. apt prefers
# Packages.gz, so tampering only with Packages proves nothing - which is
# exactly the mistake this comment exists to stop someone repeating.
rm -f "$WORK/repo/dists/stable/main/binary-$HOST_ARCH/Packages.gz"
printf '\nPackage: smuggled\n' >> "$WORK/repo/dists/stable/main/binary-$HOST_ARCH/Packages"
rm -rf /var/lib/apt/lists/*
apt-get update -o Acquire::Retries=0 2>&1 | tee "$WORK/tampered.log" || true
if ! grep -Eq "Hash Sum mismatch|Failed to fetch" "$WORK/tampered.log"; then
  echo "FAIL: apt accepted an index that does not match its checksum in Release" >&2
  exit 1
fi
echo "    apt rejected the modified index"

say "Detecting a tampered signature"
# Link two: the signature over InRelease. Alter a checksum line inside the
# signed document and the signature no longer covers what is there.
sed -i '0,/^ [0-9a-f]\{64\} /s/^ \([0-9a-f]\{63\}\)./ \1f/' "$WORK/repo/dists/stable/InRelease"
rm -f "$WORK/repo/dists/stable/Release.gpg"
rm -rf /var/lib/apt/lists/*
apt-get update -o Acquire::Retries=0 2>&1 | tee "$WORK/badsig.log" || true
if ! grep -Eq "BADSIG|signatures were invalid|not signed|GPG error" "$WORK/badsig.log"; then
  echo "FAIL: apt accepted an InRelease whose signature does not cover it" >&2
  exit 1
fi
echo "    apt rejected the modified signature"

say "Round trip complete: apt installed a package from a repository archivist built and signed"
